require "json"

module GalaxyLedger
  # DTO classes for last exchange data (user prompt + assistant response).
  # Previously stored in ledger_last-exchange.json files; now persisted as JSON
  # in the ledger_sessions.last_interaction column.
  module Exchange
    # The last exchange between user and assistant
    class LastExchange
      include JSON::Serializable

      # The user's message that started this exchange
      property user_message : String

      # Timestamp of the user message
      @[JSON::Field(key: "user_timestamp")]
      property user_timestamp : String?

      # Complete assistant response content (plain text, not ANSI styled)
      # Used for terminal display after restore
      @[JSON::Field(key: "full_content")]
      property full_content : String

      # Condensed summary for agent context injection (generated via Claude CLI extraction)
      property summary : ExchangeSummary?

      # Individual assistant messages in the exchange
      @[JSON::Field(key: "assistant_messages")]
      property assistant_messages : Array(AssistantMessage)

      def initialize(
        @user_message : String,
        @full_content : String,
        @assistant_messages : Array(AssistantMessage) = [] of AssistantMessage,
        @user_timestamp : String? = nil,
        @summary : ExchangeSummary? = nil,
      )
      end

      def to_pretty_json : String
        JSON.build(indent: "  ") do |json|
          to_json(json)
        end
      end

      # Parse a last_interaction JSON string into an array of exchanges.
      # Detects whether the JSON is a single object (legacy) or array (new).
      # Returns empty array on parse error or empty/nil input.
      def self.from_json_flexible(json_str : String?) : Array(LastExchange)
        return [] of LastExchange unless json_str
        stripped = json_str.strip
        return [] of LastExchange if stripped.empty?

        begin
          if stripped.starts_with?('[')
            Array(LastExchange).from_json(stripped)
          elsif stripped.starts_with?('{')
            [LastExchange.from_json(stripped)]
          else
            [] of LastExchange
          end
        rescue
          [] of LastExchange
        end
      end
    end

    # A single assistant message within an exchange
    class AssistantMessage
      include JSON::Serializable

      # The text content of the message
      property content : String

      # Timestamp of this message
      property timestamp : String?

      # Tool uses in this message (e.g., "Edit: path/file.rb")
      @[JSON::Field(key: "tool_uses")]
      property tool_uses : Array(String)

      def initialize(
        @content : String,
        @timestamp : String? = nil,
        @tool_uses : Array(String) = [] of String,
      )
      end
    end

    # Summary of an exchange for context injection
    # Generated by Claude CLI during learning extraction
    class ExchangeSummary
      include JSON::Serializable

      # What the user asked for
      @[JSON::Field(key: "user_request")]
      property user_request : String

      # What was accomplished (2-4 sentences with approach/reasoning)
      @[JSON::Field(key: "assistant_response")]
      property assistant_response : String

      # Files that were edited/written (not just read)
      @[JSON::Field(key: "files_modified")]
      property files_modified : Array(String)

      # Significant actions taken
      @[JSON::Field(key: "key_actions")]
      property key_actions : Array(String)

      # Decisions made during the exchange with rationale
      property decisions : Array(ExchangeDecision)?

      # Insights about codebase, gotchas, or technical facts discovered
      property learnings : Array(String)?

      def initialize(
        @user_request : String,
        @assistant_response : String,
        @files_modified : Array(String) = [] of String,
        @key_actions : Array(String) = [] of String,
        @decisions : Array(ExchangeDecision)? = nil,
        @learnings : Array(String)? = nil,
      )
      end
    end

    # A decision made during an exchange
    class ExchangeDecision
      include JSON::Serializable

      # What was chosen
      property choice : String

      # Why this approach was chosen
      property rationale : String

      # What alternatives were considered (optional)
      property alternatives : String?

      def initialize(
        @choice : String,
        @rationale : String,
        @alternatives : String? = nil,
      )
      end
    end
  end
end
