require "json"

module GalaxyLedger
  # Manages the last exchange (user prompt + assistant response) for a session
  # Stored in ledger_last-exchange.json within each session folder
  module Exchange
    # Read last exchange for a specific session
    # Returns nil if session folder or file doesn't exist (graceful degradation)
    def self.read(session_id : String) : LastExchange?
      return nil if session_id.empty?

      begin
        exchange_file = GalaxyLedger.session_dir(session_id) / LEDGER_LAST_EXCHANGE_FILENAME
        return nil unless File.exists?(exchange_file)

        json = File.read(exchange_file)
        LastExchange.from_json(json)
      rescue
        # Silently fail - return nil if we can't read or parse
        nil
      end
    end

    # Write last exchange for a specific session
    # Creates session directory if it doesn't exist
    # Returns true on success, false on failure
    def self.write(session_id : String, exchange : LastExchange) : Bool
      return false if session_id.empty?

      begin
        session_dir = GalaxyLedger.session_dir(session_id)
        Dir.mkdir_p(session_dir) unless Dir.exists?(session_dir)

        exchange_file = session_dir / LEDGER_LAST_EXCHANGE_FILENAME
        File.write(exchange_file, exchange.to_pretty_json)
        true
      rescue
        false
      end
    end

    # Check if last exchange exists for a session
    def self.exists?(session_id : String) : Bool
      return false if session_id.empty?
      File.exists?(GalaxyLedger.session_dir(session_id) / LEDGER_LAST_EXCHANGE_FILENAME)
    end

    # The last exchange between user and assistant
    class LastExchange
      include JSON::Serializable

      # The user's message that started this exchange
      property user_message : String

      # Timestamp of the user message
      @[JSON::Field(key: "user_timestamp")]
      property user_timestamp : String?

      # Complete assistant response content (plain text, not ANSI styled)
      # Used for terminal display after restore
      @[JSON::Field(key: "full_content")]
      property full_content : String

      # Condensed summary for agent context injection
      # Generated in Phase 6 via Claude CLI - nil until then
      property summary : ExchangeSummary?

      # Individual assistant messages in the exchange
      @[JSON::Field(key: "assistant_messages")]
      property assistant_messages : Array(AssistantMessage)

      def initialize(
        @user_message : String,
        @full_content : String,
        @assistant_messages : Array(AssistantMessage) = [] of AssistantMessage,
        @user_timestamp : String? = nil,
        @summary : ExchangeSummary? = nil,
      )
      end

      def to_pretty_json : String
        JSON.build(indent: "  ") do |json|
          to_json(json)
        end
      end
    end

    # A single assistant message within an exchange
    class AssistantMessage
      include JSON::Serializable

      # The text content of the message
      property content : String

      # Timestamp of this message
      property timestamp : String?

      # Tool uses in this message (e.g., "Edit: path/file.rb")
      @[JSON::Field(key: "tool_uses")]
      property tool_uses : Array(String)

      def initialize(
        @content : String,
        @timestamp : String? = nil,
        @tool_uses : Array(String) = [] of String,
      )
      end
    end

    # Summary of an exchange for context injection
    # Generated by Claude CLI during learning extraction (Phase 6)
    class ExchangeSummary
      include JSON::Serializable

      # What the user asked for
      @[JSON::Field(key: "user_request")]
      property user_request : String

      # What was accomplished
      @[JSON::Field(key: "assistant_response")]
      property assistant_response : String

      # Files that were edited/written (not just read)
      @[JSON::Field(key: "files_modified")]
      property files_modified : Array(String)

      # Significant actions taken
      @[JSON::Field(key: "key_actions")]
      property key_actions : Array(String)

      def initialize(
        @user_request : String,
        @assistant_response : String,
        @files_modified : Array(String) = [] of String,
        @key_actions : Array(String) = [] of String,
      )
      end
    end
  end
end
