name: GalaxyApp
options:
  bundleIdPrefix: com.kellyredding
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.2"

packages:
  Galactic:
    url: https://github.com/kellyredding/Galactic.git
    exactVersion: 0.1.3
  Markdown:
    url: https://github.com/swiftlang/swift-markdown.git
    from: 0.5.0

targets:
  GalaxyApp:
    type: application
    platform: macOS
    sources:
      - GalaxyApp
    info:
      path: GalaxyApp/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleDisplayName: Galaxy
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSHighResolutionCapable: true
        CFBundleIconName: AppIcon
        CFBundleURLTypes:
          - CFBundleURLName: com.kellyredding.galaxy
            CFBundleURLSchemes:
              - galaxy
    settings:
      base:
        PRODUCT_NAME: Galaxy
        PRODUCT_BUNDLE_IDENTIFIER: com.kellyredding.Galaxy
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.10"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: Galactic
        product: Galactic
      - package: Markdown
        product: Markdown
